/**
 * Generated by a one-off migration helper — do not edit by hand.
 *
 * When the ETF data pipeline moved from Postgres (auto-increment ids) to the
 * static no-DB pipeline (array-position ids), the numeric `id` of each ETF
 * changed. Portfolios saved before that switch reference the OLD ids; ones
 * saved after reference the NEW ids. These maps let the migration translate
 * a stored numeric etfId into a stable ticker, regardless of scheme.
 */

/** OLD (Postgres) id -> ticker, from the last pre-switch commit (339c77e). */
export const LEGACY_ID_TO_TICKER: Record<number, string> = {
  1: "CSPX.L",
  2: "IWDA.L",
  3: "SWRD.L",
  4: "VWCE.DE",
  5: "SSAC.L",
  6: "EIMI.L",
  7: "LCCN.L",
  8: "IASH.L",
  9: "IMEU.L",
  10: "IEUX.L",
  11: "ISF.L",
  12: "SJPA.L",
  13: "NDIA.L",
  14: "CPXJ.L",
  15: "AEJL.L",
  16: "CNDX.L",
  17: "EQQQ.L",
  18: "WITS.L",
  19: "WHEA.L",
  20: "WFIN.L",
  21: "WCOD.L",
  22: "WENS.L",
  23: "SMGB.L",
  24: "WTAI.L",
  25: "RBOT.L",
  26: "WCLD.L",
  27: "WCBR.L",
  28: "ISPY.L",
  29: "NATO.L",
  30: "INRG.L",
  31: "URNM.L",
  32: "NUCL.L",
  33: "SGLN.L",
  34: "DH2O.L",
  35: "AGED.L",
  36: "LITU.L",
  37: "AGGG.L",
  148: "CSKR.L",
  149: "XMTW.L",
  150: "EMXC.L",
  151: "XVTD.L",
  152: "XMBR.L",
  153: "XMES.L",
  154: "IKSA.L",
  199: "SUSW.L",
  200: "SUUS.L",
  201: "SUSM.L",
  246: "LUXG.L",
  247: "IWDP.L",
  248: "VHYL.L",
  296: "HEAL.L",
  297: "YODA.L",
  298: "ESPO.L",
  299: "EBIZ.L",
  350: "HSTC.L",
  405: "DFNS.L",
};

/** NEW (static) id -> ticker, from the current data. */
export const CURRENT_ID_TO_TICKER: Record<number, string> = {
  1: "CSPX.L",
  2: "IWDA.L",
  3: "SWRD.L",
  4: "VWCE.DE",
  5: "SSAC.L",
  6: "EIMI.L",
  7: "LCCN.L",
  8: "IASH.L",
  9: "IMEU.L",
  10: "IEUX.L",
  11: "ISF.L",
  12: "SJPA.L",
  13: "NDIA.L",
  14: "CPXJ.L",
  15: "AEJL.L",
  16: "CNDX.L",
  17: "EQQQ.L",
  18: "WITS.L",
  19: "WHEA.L",
  20: "WFIN.L",
  21: "WCOD.L",
  22: "WENS.L",
  23: "SMGB.L",
  24: "WTAI.L",
  25: "RBOT.L",
  26: "WCLD.L",
  27: "WCBR.L",
  28: "ISPY.L",
  29: "NATO.L",
  30: "INRG.L",
  31: "URNM.L",
  32: "NUCL.L",
  33: "SGLN.L",
  34: "DH2O.L",
  35: "AGED.L",
  36: "LITU.L",
  37: "CSKR.L",
  38: "XMTW.L",
  39: "EMXC.L",
  40: "XVTD.L",
  41: "XMBR.L",
  42: "XMES.L",
  43: "IKSA.L",
  44: "DFNS.L",
  45: "HSTC.L",
  46: "HEAL.L",
  47: "YODA.L",
  48: "ESPO.L",
  49: "EBIZ.L",
  50: "LUXG.L",
  51: "IWDP.L",
  52: "VHYL.L",
  53: "SUSW.L",
  54: "SUUS.L",
  55: "SUSM.L",
  56: "AGGG.L",
};

/** Highest id in the new (dense) scheme — anything above is unambiguously old. */
export const MAX_NEW_ID = 56;

/**
 * UTC moment the live site started serving new-scheme ids. Portfolios whose
 * updatedAt is before this used the old scheme; after, the new scheme. Only
 * used to break ties for ids <= MAX_NEW_ID where old and new disagree.
 */
export const ID_SWITCH_CUTOFF_MS = Date.parse("2026-05-30T07:00:00.000Z");
