/**
 * Download logos for SPECIFIC tickers and MERGE them into the existing
 * manifest — without re-fetching the whole set.
 *
 * The full download-logos script rewrites lib/data/logo-manifest.ts from
 * scratch based on whatever succeeds that run, so a transient failure on
 * an existing logo would silently drop it. This only touches the tickers
 * you pass, preserving every other manifest entry.
 *
 * Usage: npx tsx scripts/download-some-logos.ts AIR.PA SAF.PA HO.PA …
 */

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import path from "node:path";
import { STOCK_DOMAINS } from "../lib/data/stock-logos";
import { LOGO_FILES } from "../lib/data/logo-manifest";

const LOGO_DIR = path.resolve(process.cwd(), "public", "logos");
const MANIFEST_PATH = path.resolve(process.cwd(), "lib", "data", "logo-manifest.ts");

const EXT_BY_TYPE: Record<string, string> = {
  "image/png": "png",
  "image/x-icon": "ico",
  "image/vnd.microsoft.icon": "ico",
  "image/svg+xml": "svg",
  "image/jpeg": "jpg",
  "image/gif": "gif",
  "image/webp": "webp",
};

async function downloadOne(ticker: string, domain: string): Promise<string | null> {
  const sources = [
    `https://icon.horse/icon/${domain}`,
    `https://www.google.com/s2/favicons?domain=${domain}&sz=128`,
  ];
  for (const url of sources) {
    try {
      const res = await fetch(url, { redirect: "follow" });
      if (!res.ok) continue;
      const ct = (res.headers.get("content-type") ?? "").split(";")[0].trim();
      const ext = EXT_BY_TYPE[ct] ?? "png";
      const buf = Buffer.from(await res.arrayBuffer());
      if (buf.length < 100) continue;
      const filename = `${ticker}.${ext}`;
      writeFileSync(path.join(LOGO_DIR, filename), buf);
      return filename;
    } catch {
      // try next source
    }
  }
  return null;
}

async function main() {
  const tickers = process.argv.slice(2);
  if (tickers.length === 0) {
    console.error("Usage: npx tsx scripts/download-some-logos.ts <TICKER> [<TICKER> …]");
    process.exit(1);
  }
  if (!existsSync(LOGO_DIR)) mkdirSync(LOGO_DIR, { recursive: true });

  const manifest: Record<string, string> = { ...LOGO_FILES };
  let ok = 0;
  const failures: string[] = [];

  for (const ticker of tickers) {
    const domain = STOCK_DOMAINS[ticker];
    if (!domain) {
      console.log(`  ✗ ${ticker} — no domain in STOCK_DOMAINS`);
      failures.push(ticker);
      continue;
    }
    const file = await downloadOne(ticker, domain);
    if (file) {
      manifest[ticker] = file;
      ok++;
      console.log(`  ✓ ${ticker.padEnd(8)} → ${file}`);
    } else {
      failures.push(ticker);
      console.log(`  ✗ ${ticker} — no logo from ${domain}`);
    }
  }

  const sortedKeys = Object.keys(manifest).sort();
  const body = sortedKeys
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(manifest[k])},`)
    .join("\n");
  const manifestFile = `/**
 * Generated by scripts/download-logos.ts — do not edit by hand.
 * Maps a ticker to its locally-cached logo filename under /public/logos/.
 */
export const LOGO_FILES: Record<string, string> = {
${body}
};
`;
  writeFileSync(MANIFEST_PATH, manifestFile);

  console.log(`\nDone. ${ok} downloaded, ${failures.length} failed${failures.length ? ` (${failures.join(", ")})` : ""}.`);
  console.log(`Merged into lib/data/logo-manifest.ts (${sortedKeys.length} total).`);
  process.exit(failures.length ? 1 : 0);
}

main().catch((err) => {
  console.error("Logo download failed:", err);
  process.exit(1);
});
