/**
 * Download every ticker's logo once and save it locally so the app
 * serves logos from its own deployment instead of hitting icon.horse on
 * every page load.
 *
 *   - public/logos/{TICKER}.{ext} — the logo bytes
 *   - lib/data/logo-manifest.ts   — ticker → filename map (imported by the
 *     StockLogo component)
 *
 * Sources tried per ticker, in order:
 *   1. icon.horse (good quality, no auth)
 *   2. Google favicon (universal fallback)
 *
 * Run: npm run logos:download
 */

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import path from "node:path";
import { STOCK_DOMAINS } from "../lib/data/stock-logos";

const LOGO_DIR = path.resolve(process.cwd(), "public", "logos");
const MANIFEST_PATH = path.resolve(process.cwd(), "lib", "data", "logo-manifest.ts");
const BATCH_SIZE = 6;

const EXT_BY_TYPE: Record<string, string> = {
  "image/png": "png",
  "image/x-icon": "ico",
  "image/vnd.microsoft.icon": "ico",
  "image/svg+xml": "svg",
  "image/jpeg": "jpg",
  "image/gif": "gif",
  "image/webp": "webp",
};

async function downloadOne(
  ticker: string,
  domain: string,
): Promise<string | null> {
  const sources = [
    `https://icon.horse/icon/${domain}`,
    `https://www.google.com/s2/favicons?domain=${domain}&sz=128`,
  ];
  for (const url of sources) {
    try {
      const res = await fetch(url, { redirect: "follow" });
      if (!res.ok) continue;
      const ct = (res.headers.get("content-type") ?? "").split(";")[0].trim();
      const ext = EXT_BY_TYPE[ct] ?? "png";
      const buf = Buffer.from(await res.arrayBuffer());
      if (buf.length < 100) continue; // empty / placeholder
      const filename = `${ticker}.${ext}`;
      writeFileSync(path.join(LOGO_DIR, filename), buf);
      return filename;
    } catch {
      // try next source
    }
  }
  return null;
}

async function main() {
  if (!existsSync(LOGO_DIR)) mkdirSync(LOGO_DIR, { recursive: true });

  const entries = Object.entries(STOCK_DOMAINS);
  console.log(`Downloading ${entries.length} logos…`);

  const manifest: Record<string, string> = {};
  let ok = 0;
  let failed = 0;

  for (let i = 0; i < entries.length; i += BATCH_SIZE) {
    const batch = entries.slice(i, i + BATCH_SIZE);
    const results = await Promise.all(
      batch.map(async ([ticker, domain]) => {
        const file = await downloadOne(ticker, domain);
        return { ticker, file };
      }),
    );
    for (const { ticker, file } of results) {
      if (file) {
        manifest[ticker] = file;
        ok++;
        console.log(`  ✓ ${ticker.padEnd(8)} → ${file}`);
      } else {
        failed++;
        console.log(`  ✗ ${ticker} — no logo`);
      }
    }
  }

  // Write the manifest as a typed module
  const sortedKeys = Object.keys(manifest).sort();
  const body = sortedKeys
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(manifest[k])},`)
    .join("\n");
  const manifestFile = `/**
 * Generated by scripts/download-logos.ts — do not edit by hand.
 * Maps a ticker to its locally-cached logo filename under /public/logos/.
 */
export const LOGO_FILES: Record<string, string> = {
${body}
};
`;
  writeFileSync(MANIFEST_PATH, manifestFile);

  console.log(`\nDone. ${ok} OK, ${failed} failed.`);
  console.log(`Wrote ${ok} files to public/logos/ + lib/data/logo-manifest.ts`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Logo download failed:", err);
  process.exit(1);
});
