/**
 * Curated list of 37 ETFs (mostly UCITS Irish-domiciled, plus one gold ETC)
 * available on IBKR Singapore. All tickers verified against Yahoo Finance.
 *
 * `friendlyName` is the plain-language nickname shown as the primary heading.
 * `name` is the official fund name (small supporting text).
 * `shortDescription` adds one extra detail beyond the nickname.
 *
 * Source: /Users/mb/Desktop/Local Apps/etf-portfolio/docs/ticker-research.md
 */

import type { NewEtf } from "@/lib/db/schema";

export const seedEtfs: NewEtf[] = [
  // ─── Broad market ──────────────────────────────────────────────────────
  {
    ticker: "CSPX.L",
    isin: "IE00B5BMR087",
    friendlyName: "The biggest 500 US companies",
    name: "iShares Core S&P 500 UCITS ETF",
    shortDescription:
      "Heavily tech-weighted — about a quarter sits in Apple, Microsoft, Nvidia and a few other giants.",
    longDescription:
      "Tracks the S&P 500 index of the 500 largest US-listed companies. The most liquid Irish-domiciled S&P 500 tracker, with very low fees. Around a quarter of the index is concentrated in the top 10 names, most of them mega-cap tech.",
    category: "broad_market",
    subCategory: "us_large_cap",
    ter: "0.0007",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "S&P 500",
    tags: ["us", "large-cap", "core", "low-cost"],
  },
  {
    ticker: "IWDA.L",
    isin: "IE00B4L5Y983",
    friendlyName: "Developed-world stocks",
    name: "iShares Core MSCI World UCITS ETF",
    shortDescription:
      "About 1,500 companies across 23 wealthy countries. Around 70% US by weight.",
    longDescription:
      "Tracks the MSCI World index — developed markets only (no emerging). The default 'world ex-EM' building block for Singapore residents on IBKR. Around 70% US-weighted by market cap.",
    category: "broad_market",
    subCategory: "world_developed",
    ter: "0.0020",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "MSCI World",
    tags: ["world", "developed", "core"],
  },
  {
    ticker: "SWRD.L",
    isin: "IE00BFY0GT14",
    friendlyName: "Developed-world stocks (cheaper)",
    name: "SPDR MSCI World UCITS ETF",
    shortDescription:
      "Same index as the iShares version above, but with a lower annual fee.",
    longDescription:
      "Same index as IWDA.L (MSCI World) but with a lower TER. Slightly shorter track record (listed 2019). Good choice if you want minimum fees on a world tracker.",
    category: "broad_market",
    subCategory: "world_developed",
    ter: "0.0012",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 3,
    issuer: "SPDR",
    benchmark: "MSCI World",
    tags: ["world", "developed", "core", "low-cost"],
  },
  {
    ticker: "VWCE.DE",
    isin: "IE00BK5BQT80",
    friendlyName: "All world stocks (incl. emerging)",
    name: "Vanguard FTSE All-World UCITS ETF",
    shortDescription:
      "About 3,700 companies — developed AND emerging markets in one fund.",
    longDescription:
      "Vanguard's global all-cap tracker, covering both developed and emerging markets in a single fund. Trades on Xetra in EUR; the LSE USD line is VWRA.L for the same fund.",
    category: "broad_market",
    subCategory: "world_all_country",
    ter: "0.0022",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "Xetra",
    currency: "EUR",
    riskScore: 3,
    issuer: "Vanguard",
    benchmark: "FTSE All-World",
    tags: ["world", "global", "developed", "emerging", "core"],
  },
  {
    ticker: "SSAC.L",
    isin: "IE00B6R52259",
    friendlyName: "All world stocks (iShares version)",
    name: "iShares MSCI ACWI UCITS ETF",
    shortDescription:
      "iShares' equivalent of the Vanguard all-world fund — slightly different index, very similar holdings.",
    longDescription:
      "iShares MSCI ACWI — alternative to VWCE.DE. Tracks the MSCI All Country World Index (developed + emerging). Trades on LSE in GBp; the USD line of the same fund is ISAC.L.",
    category: "broad_market",
    subCategory: "world_all_country",
    ter: "0.0020",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "MSCI ACWI",
    tags: ["world", "global", "developed", "emerging", "core"],
  },

  // ─── Emerging markets ──────────────────────────────────────────────────
  {
    ticker: "EIMI.L",
    isin: "IE00BKM4GZ66",
    friendlyName: "Emerging-market stocks",
    name: "iShares Core MSCI EM IMI UCITS ETF",
    shortDescription:
      "About 3,000 companies across 24 emerging countries — China, Taiwan, India and Korea lead.",
    longDescription:
      "Broad, low-cost emerging-markets exposure including small caps (IMI = Investable Market Index). China, Taiwan, India and Korea dominate by weight.",
    category: "broad_market",
    subCategory: "emerging_markets",
    ter: "0.0018",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 4,
    issuer: "iShares",
    benchmark: "MSCI EM IMI",
    tags: ["emerging", "core", "global"],
  },
  {
    ticker: "LCCN.L",
    isin: "LU1841731745",
    friendlyName: "Chinese companies (broad)",
    name: "Amundi MSCI China UCITS ETF",
    shortDescription:
      "Includes Hong Kong-listed, US-listed (ADRs) and mainland Chinese companies together.",
    longDescription:
      "Tracks the MSCI China index, covering Chinese companies listed in Hong Kong, the US (ADRs), and mainland China (A-shares via Stock Connect). Higher concentration risk than EIMI.",
    category: "region",
    subCategory: "china",
    ter: "0.0040",
    domicile: "Luxembourg",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "Amundi",
    benchmark: "MSCI China",
    tags: ["china", "asia", "emerging", "thematic-country"],
  },
  {
    ticker: "IASH.L",
    isin: "IE00BQT3WG13",
    friendlyName: "Mainland China stocks only",
    name: "iShares MSCI China A UCITS ETF",
    shortDescription:
      "Only stocks listed in Shanghai and Shenzhen — different from Hong Kong-listed Chinese stocks.",
    longDescription:
      "Tracks A-shares listed in Shanghai and Shenzhen — meaningfully different from HK-listed Chinese stocks. Trades on LSE in GBp; the USD line is CNYA.L.",
    category: "region",
    subCategory: "china_a_shares",
    ter: "0.0040",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 5,
    issuer: "iShares",
    benchmark: "MSCI China A",
    tags: ["china", "a-shares", "asia", "emerging"],
  },

  // ─── Developed regions ─────────────────────────────────────────────────
  {
    ticker: "IMEU.L",
    isin: "IE00B4K48X80",
    friendlyName: "European stocks (incl. UK)",
    name: "iShares Core MSCI Europe UCITS ETF",
    shortDescription:
      "About 430 large/mid-cap companies — Nestlé, ASML, LVMH, Novo Nordisk, AstraZeneca, etc.",
    longDescription:
      "Broad Europe developed-market exposure. Distributing share class. The accumulating sister is IEUA.L.",
    category: "region",
    subCategory: "europe_developed",
    ter: "0.0012",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "MSCI Europe",
    tags: ["europe", "developed"],
  },
  {
    ticker: "IEUX.L",
    isin: "IE00B14X4N27",
    friendlyName: "European stocks (no UK)",
    name: "iShares MSCI Europe ex-UK UCITS ETF",
    shortDescription:
      "Continental Europe only — Germany, France, Switzerland-heavy. Useful if you also hold a UK fund.",
    longDescription:
      "MSCI Europe ex-UK — useful when paired with ISF.L for explicit UK weighting control. Distributing share class.",
    category: "region",
    subCategory: "europe_ex_uk",
    ter: "0.0040",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "MSCI Europe ex-UK",
    tags: ["europe", "developed", "ex-uk"],
  },
  {
    ticker: "ISF.L",
    isin: "IE0005042456",
    friendlyName: "Biggest UK companies",
    name: "iShares Core FTSE 100 UCITS ETF",
    shortDescription:
      "The 100 biggest companies on the London Stock Exchange — heavy in oil, banks and pharma.",
    longDescription:
      "Most liquid UK large-cap ETF. Distributing. Heavy in financials, energy, and consumer staples (Shell, BP, HSBC, AstraZeneca).",
    category: "region",
    subCategory: "uk_large_cap",
    ter: "0.0007",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "FTSE 100",
    tags: ["uk", "developed", "large-cap"],
  },
  {
    ticker: "SJPA.L",
    isin: "IE00B4L5YX21",
    friendlyName: "Japanese stocks",
    name: "iShares Core MSCI Japan IMI UCITS ETF",
    shortDescription:
      "About 200 Japanese companies — Toyota, Sony, Mitsubishi, Keyence, etc.",
    longDescription:
      "Broad Japan exposure. Trades on LSE in GBp; the USD line is IJPA.L.",
    category: "region",
    subCategory: "japan",
    ter: "0.0012",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "MSCI Japan IMI",
    tags: ["japan", "developed", "asia"],
  },

  // ─── India ──────────────────────────────────────────────────────────────
  {
    ticker: "NDIA.L",
    isin: "IE00BZCQB185",
    friendlyName: "Indian stocks",
    name: "iShares MSCI India UCITS ETF",
    shortDescription:
      "Large and mid-sized Indian companies. High growth potential, but volatile and rupee-exposed.",
    longDescription:
      "Tracks the MSCI India index. India is structurally one of the highest-growth emerging markets, but volatility is high and the ETF has a notable currency risk (INR exposure).",
    category: "region",
    subCategory: "india",
    ter: "0.0065",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "iShares",
    benchmark: "MSCI India",
    tags: ["india", "emerging", "asia", "thematic-country"],
  },

  // ─── Asia-Pacific ──────────────────────────────────────────────────────
  {
    ticker: "CPXJ.L",
    isin: "IE00B52MJY50",
    friendlyName: "Asia-Pacific developed countries",
    name: "iShares Core MSCI Pacific ex-Japan UCITS ETF",
    shortDescription:
      "Australia, Hong Kong, Singapore, New Zealand — wealthy Asia-Pacific minus Japan.",
    longDescription:
      "Developed Asia-Pacific excluding Japan. Heavily weighted toward Australia and Hong Kong.",
    category: "region",
    subCategory: "asia_pacific_ex_japan",
    ter: "0.0020",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "MSCI Pacific ex-Japan",
    tags: ["asia", "developed", "pacific"],
  },
  {
    ticker: "AEJL.L",
    friendlyName: "All Asia-Pacific (incl. emerging)",
    name: "Amundi MSCI AC Asia Pacific ex Japan UCITS ETF",
    shortDescription:
      "Includes both developed (Australia, HK, SG) and emerging (China, India, Korea, Taiwan) — no Japan.",
    longDescription:
      "Includes both developed (Australia, HK, SG, NZ) and emerging (China, India, Korea, Taiwan) Asia-Pacific markets ex-Japan. Partially overlaps with EIMI.L on the EM side.",
    category: "region",
    subCategory: "asia_pacific_all_country",
    ter: "0.0045",
    domicile: "Luxembourg",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 4,
    issuer: "Amundi",
    benchmark: "MSCI AC Asia Pacific ex-Japan",
    tags: ["asia", "pacific", "all-country"],
  },

  // ─── Nasdaq / US tech ──────────────────────────────────────────────────
  {
    ticker: "CNDX.L",
    isin: "IE00BYVQ9F29",
    friendlyName: "Top 100 US tech & growth companies",
    name: "iShares NASDAQ 100 UCITS ETF",
    shortDescription:
      "The 100 largest non-bank Nasdaq companies — Apple, Microsoft, Nvidia, Amazon, Meta, etc.",
    longDescription:
      "Concentrated US tech and growth exposure (Apple, Microsoft, Nvidia, etc.). High overlap with the top of CSPX. Accumulating share class.",
    category: "sector",
    subCategory: "us_nasdaq",
    ter: "0.0030",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 4,
    issuer: "iShares",
    benchmark: "NASDAQ-100",
    tags: ["us", "nasdaq", "tech", "growth"],
  },
  {
    ticker: "EQQQ.L",
    isin: "IE0032077012",
    friendlyName: "Top 100 US tech & growth (Invesco version)",
    name: "Invesco EQQQ NASDAQ-100 UCITS ETF",
    shortDescription:
      "Same Nasdaq 100 index as the iShares version — but pays dividends instead of reinvesting them.",
    longDescription:
      "Same Nasdaq 100 index as CNDX.L but distributing. The accumulating sister line is EQAC.L.",
    category: "sector",
    subCategory: "us_nasdaq",
    ter: "0.0030",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 4,
    issuer: "Invesco",
    benchmark: "NASDAQ-100",
    tags: ["us", "nasdaq", "tech", "growth"],
  },

  // ─── World sectors ─────────────────────────────────────────────────────
  {
    ticker: "WITS.L",
    friendlyName: "Tech companies worldwide",
    name: "iShares MSCI World IT Sector Advanced UCITS ETF",
    shortDescription:
      "Information-technology companies across developed markets. Less than 2 years of history.",
    longDescription:
      "Newer fund (listed Jan 2024) — less than 2 years of price history. Heavily concentrated in Microsoft, Apple, Nvidia.",
    category: "sector",
    subCategory: "world_it",
    ter: "0.0018",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "GBP",
    riskScore: 4,
    issuer: "iShares",
    benchmark: "MSCI World Information Technology",
    tags: ["world", "sector", "tech", "short-history"],
  },
  {
    ticker: "WHEA.L",
    isin: "IE00BYTRRD19",
    friendlyName: "Healthcare companies worldwide",
    name: "SPDR MSCI World Health Care UCITS ETF",
    shortDescription:
      "Pharma, biotech, medical devices, hospitals — usually less volatile than tech.",
    longDescription:
      "Pharma, biotech, medical devices, and health services across developed markets. Lower volatility than tech-heavy sectors.",
    category: "sector",
    subCategory: "world_health_care",
    ter: "0.0030",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 3,
    issuer: "SPDR",
    benchmark: "MSCI World Health Care",
    tags: ["world", "sector", "healthcare", "defensive"],
  },
  {
    ticker: "WFIN.L",
    isin: "IE00BYTRRB95",
    friendlyName: "Banks & finance worldwide",
    name: "SPDR MSCI World Financials UCITS ETF",
    shortDescription:
      "Banks, insurers, asset managers. Sensitive to interest rates and recessions.",
    longDescription:
      "Cyclical sector — sensitive to interest rates and credit cycles.",
    category: "sector",
    subCategory: "world_financials",
    ter: "0.0030",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 3,
    issuer: "SPDR",
    benchmark: "MSCI World Financials",
    tags: ["world", "sector", "financials", "cyclical"],
  },
  {
    ticker: "WCOD.L",
    isin: "IE00BYTRR863",
    friendlyName: "Consumer brands worldwide",
    name: "SPDR MSCI World Consumer Discretionary UCITS ETF",
    shortDescription:
      "Cars, retail, restaurants, luxury — Tesla, Amazon, LVMH, Toyota. Cyclical.",
    longDescription:
      "Tesla, Amazon, LVMH, Toyota, etc. Cyclical sector — performs well in expansions, badly in recessions.",
    category: "sector",
    subCategory: "world_consumer_discretionary",
    ter: "0.0030",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 3,
    issuer: "SPDR",
    benchmark: "MSCI World Consumer Discretionary",
    tags: ["world", "sector", "consumer", "cyclical"],
  },
  {
    ticker: "WENS.L",
    friendlyName: "Oil & gas companies",
    name: "iShares MSCI World Energy Sector UCITS ETF",
    shortDescription:
      "ExxonMobil, Chevron, Shell, TotalEnergies, BP. Performance tracks the oil price.",
    longDescription:
      "Exxon, Chevron, Shell, TotalEnergies, BP. Strongly cyclical and oil-price sensitive. Distributing share class; Acc sister is WNRG.L.",
    category: "sector",
    subCategory: "world_energy",
    ter: "0.0018",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "GBP",
    riskScore: 4,
    issuer: "iShares",
    benchmark: "MSCI World Energy",
    tags: ["world", "sector", "energy", "oil", "cyclical"],
  },

  // ─── Thematic tech ─────────────────────────────────────────────────────
  {
    ticker: "SMGB.L",
    isin: "IE00BMC38736",
    friendlyName: "Chip makers (semiconductors)",
    name: "VanEck Semiconductor UCITS ETF",
    shortDescription:
      "Companies designing or making computer chips — Nvidia, TSMC, ASML, Broadcom, AMD.",
    longDescription:
      "TSMC, Nvidia, ASML, Broadcom, AMD — top names are heavily weighted. Highly cyclical and highly volatile. USD trading line: SMGP.L.",
    category: "thematic",
    subCategory: "semiconductors",
    ter: "0.0035",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "GBP",
    riskScore: 5,
    issuer: "VanEck",
    benchmark: "MVIS US Listed Semiconductor 25",
    tags: ["tech", "thematic", "semiconductors", "ai"],
  },
  {
    ticker: "WTAI.L",
    isin: "IE00BDVPNG13",
    friendlyName: "AI companies",
    name: "WisdomTree Artificial Intelligence UCITS ETF",
    shortDescription:
      "Mix of chipmakers, AI-software companies, and businesses deploying AI. Volatile.",
    longDescription:
      "Mix of chipmakers, software vendors, and AI-application companies. Concentrated and volatile.",
    category: "thematic",
    subCategory: "ai",
    ter: "0.0040",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "WisdomTree",
    benchmark: "Nasdaq CTA AI",
    tags: ["tech", "thematic", "ai", "growth"],
  },
  {
    ticker: "RBOT.L",
    isin: "IE00BYZK4552",
    friendlyName: "Robotics & automation",
    name: "iShares Automation & Robotics UCITS ETF",
    shortDescription:
      "Industrial automation, robotics, and factory-tech specialists.",
    longDescription:
      "Industrial automation companies, robotics specialists, and AI-adjacent industrials. Less concentrated than pure AI ETFs.",
    category: "thematic",
    subCategory: "robotics",
    ter: "0.0040",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "iShares",
    benchmark: "iSTOXX FactSet Automation & Robotics",
    tags: ["tech", "thematic", "robotics", "automation"],
  },
  {
    ticker: "WCLD.L",
    isin: "IE00BJGWQN72",
    friendlyName: "Cloud & SaaS companies",
    name: "WisdomTree Cloud Computing UCITS ETF",
    shortDescription:
      "Smaller, fast-growing cloud-software companies. More volatile than mega-cap tech.",
    longDescription:
      "Tracks the BVP Nasdaq Emerging Cloud index — small-cap heavy and meaningfully more volatile than mega-cap cloud names. Snowflake, Datadog, CrowdStrike etc.",
    category: "thematic",
    subCategory: "cloud",
    ter: "0.0040",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "WisdomTree",
    benchmark: "BVP Nasdaq Emerging Cloud",
    tags: ["tech", "thematic", "cloud", "saas", "small-cap"],
  },

  // ─── Cybersecurity ─────────────────────────────────────────────────────
  {
    ticker: "WCBR.L",
    isin: "IE00BLPK3577",
    friendlyName: "Cybersecurity companies",
    name: "WisdomTree Cybersecurity UCITS ETF",
    shortDescription:
      "Companies protecting against cyber attacks — CrowdStrike, Palo Alto, Zscaler, Fortinet.",
    longDescription:
      "Palo Alto Networks, CrowdStrike, Zscaler, Fortinet etc. Narrower and more focused than ISPY.",
    category: "thematic",
    subCategory: "cybersecurity",
    ter: "0.0045",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "WisdomTree",
    benchmark: "WisdomTree Team8 Cybersecurity",
    tags: ["tech", "thematic", "cybersecurity"],
  },
  {
    ticker: "ISPY.L",
    isin: "IE00BYPLS672",
    friendlyName: "Cybersecurity (longer history)",
    name: "L&G Cyber Security UCITS ETF",
    shortDescription:
      "Same theme as the WisdomTree fund, but with about 10 years of price history.",
    longDescription:
      "The longest-history UCITS cyber ETF — preferred for back-testing. Higher TER than WCBR. Distributing.",
    category: "thematic",
    subCategory: "cybersecurity",
    ter: "0.0069",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 5,
    issuer: "L&G",
    benchmark: "ISE Cyber Security UCITS",
    tags: ["tech", "thematic", "cybersecurity"],
  },

  // ─── Defence ────────────────────────────────────────────────────────────
  {
    ticker: "NATO.L",
    isin: "IE000OJ5TQP4",
    friendlyName: "Defence companies",
    name: "HANetf Future of Defence UCITS ETF",
    shortDescription:
      "Weapons and defence contractors in NATO countries — Lockheed Martin, RTX, BAE, Rheinmetall.",
    longDescription:
      "Lockheed Martin, RTX, Northrop Grumman, BAE Systems, Rheinmetall etc. Highly concentrated. New fund (2023), so back-tests are short.",
    category: "thematic",
    subCategory: "defence",
    ter: "0.0049",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 4,
    issuer: "HANetf",
    benchmark: "EQM Future of Defence",
    tags: ["thematic", "defence", "aerospace"],
  },

  // ─── Energy / commodities ──────────────────────────────────────────────
  {
    ticker: "INRG.L",
    isin: "IE00B1XNHC34",
    friendlyName: "Clean energy (solar, wind, etc.)",
    name: "iShares Global Clean Energy Transition UCITS ETF",
    shortDescription:
      "Solar, wind, hydrogen, energy storage. Volatile and sensitive to interest rates.",
    longDescription:
      "Solar (First Solar, Enphase), wind (Vestas, Orsted), and broader transition plays. Highly volatile; sensitive to interest rates.",
    category: "thematic",
    subCategory: "clean_energy",
    ter: "0.0065",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 5,
    issuer: "iShares",
    benchmark: "S&P Global Clean Energy Transition",
    tags: ["thematic", "energy", "clean-energy", "esg"],
  },
  {
    ticker: "URNM.L",
    isin: "IE0005YK6564",
    friendlyName: "Uranium miners",
    name: "Sprott Uranium Miners UCITS ETF",
    shortDescription:
      "Companies that mine uranium for nuclear fuel — Cameco, Kazatomprom, NexGen.",
    longDescription:
      "Cameco, Kazatomprom, NexGen — the upstream of the nuclear fuel cycle. Highly cyclical (commodity price driven) and concentrated.",
    category: "thematic",
    subCategory: "uranium",
    ter: "0.0085",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "Sprott",
    benchmark: "North Shore Global Uranium Mining",
    tags: ["thematic", "energy", "uranium", "nuclear", "commodities"],
  },
  {
    ticker: "NUCL.L",
    isin: "IE000M7V94E1",
    friendlyName: "Nuclear & uranium broad",
    name: "VanEck Uranium and Nuclear Technologies UCITS ETF",
    shortDescription:
      "Whole nuclear value chain — miners, utilities running plants, reactor and tech providers.",
    longDescription:
      "Broader than URNM — adds nuclear utilities and reactor/technology companies. Complements URNM if you want the full nuclear value chain.",
    category: "thematic",
    subCategory: "nuclear",
    ter: "0.0055",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 4,
    issuer: "VanEck",
    benchmark: "MarketVector Global Uranium and Nuclear Energy Infrastructure",
    tags: ["thematic", "energy", "uranium", "nuclear"],
  },
  {
    ticker: "SGLN.L",
    friendlyName: "Physical gold",
    name: "iShares Physical Gold ETC",
    shortDescription:
      "Backed by gold held in vaults. Tracks the gold price. Defensive — tends to hold up in crises.",
    longDescription:
      "An Exchange-Traded Commodity (not a UCITS fund) backed by physical gold. Functions like a gold-spot tracker. Domiciled in Jersey under iShares Physical Metals plc.",
    category: "commodity",
    subCategory: "gold",
    ter: "0.0012",
    domicile: "Jersey",
    isUcits: false,
    isAccumulating: null,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "LBMA Gold Price",
    tags: ["commodity", "gold", "defensive", "etc"],
  },

  // ─── Other thematic ────────────────────────────────────────────────────
  {
    ticker: "DH2O.L",
    isin: "IE00B1TXK627",
    friendlyName: "Water companies",
    name: "iShares Global Water UCITS ETF",
    shortDescription:
      "Water utilities and water-infrastructure businesses — Veolia, American Water Works, Xylem.",
    longDescription:
      "Veolia, American Water Works, Xylem etc. Mix of regulated utilities (lower vol) and industrials. Distributing.",
    category: "thematic",
    subCategory: "water",
    ter: "0.0065",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "USD",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "S&P Global Water",
    tags: ["thematic", "water", "infrastructure", "esg"],
  },
  {
    ticker: "AGED.L",
    isin: "IE00BYZK4669",
    friendlyName: "Aging-population businesses",
    name: "iShares Ageing Population UCITS ETF",
    shortDescription:
      "Pharma, retirement services, products geared toward older people.",
    longDescription:
      "Pharma, healthcare facilities, financial services for retirees, and consumer staples geared to older demographics.",
    category: "thematic",
    subCategory: "demographics",
    ter: "0.0040",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "iSTOXX FactSet Ageing Population",
    tags: ["thematic", "demographics", "ageing", "healthcare"],
  },
  {
    ticker: "LITU.L",
    isin: "IE0002PG6CA6",
    friendlyName: "Lithium & batteries",
    name: "Global X Lithium & Battery Tech UCITS ETF",
    shortDescription:
      "Lithium miners and battery makers — Albemarle, SQM, CATL, BYD, LG Chem. Tracks EV demand.",
    longDescription:
      "Albemarle, SQM, CATL, BYD, LG Chem etc. Highly cyclical — performance closely tracks lithium prices and EV demand.",
    category: "thematic",
    subCategory: "lithium_batteries",
    ter: "0.0060",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "Global X",
    benchmark: "Solactive Global Lithium",
    tags: ["thematic", "lithium", "batteries", "ev", "commodities"],
  },

  // ─── Additional emerging-market countries ──────────────────────
  {
    ticker: "CSKR.L",
    isin: "IE00B0M63391",
    friendlyName: "Korean stocks (Samsung, Hyundai)",
    name: "iShares MSCI Korea UCITS ETF USD (Acc)",
    shortDescription:
      "Samsung Electronics, SK Hynix, Hyundai Motor, LG Energy Solution and other large Korean companies.",
    longDescription:
      "Tracks the MSCI Korea index. Samsung dominates the index. South Korea sits on the line between developed and emerging — MSCI classifies it as EM. High exposure to tech/semis and to global cyclical demand.",
    category: "region",
    subCategory: "korea",
    ter: "0.0074",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "iShares",
    benchmark: "MSCI Korea",
    tags: ["korea", "asia", "emerging", "tech", "samsung"],
  },
  {
    ticker: "XMTW.L",
    friendlyName: "Taiwanese stocks (TSMC-heavy)",
    name: "Xtrackers MSCI Taiwan UCITS ETF 1C",
    shortDescription:
      "Dominated by TSMC (around half the index), plus Hon Hai, MediaTek and other Taiwanese tech and industrials.",
    longDescription:
      "Tracks MSCI Taiwan. TSMC is roughly 45-50% of the index — this is essentially a concentrated bet on global semiconductor demand and Taiwan's chip industry. Trades in GBp on LSE, so there's an extra FX hop for SGD-base investors.",
    category: "region",
    subCategory: "taiwan",
    ter: "0.0065",
    domicile: "Luxembourg",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 5,
    issuer: "Xtrackers",
    benchmark: "MSCI Taiwan",
    tags: ["taiwan", "asia", "emerging", "tech", "semiconductors", "tsmc"],
  },
  {
    ticker: "EMXC.L",
    friendlyName: "Emerging markets without China",
    name: "Amundi MSCI Emerging Markets ex China UCITS ETF",
    shortDescription:
      "Broad emerging-market exposure (India, Korea, Taiwan, Brazil, Saudi, Mexico…) with mainland China and Hong Kong excluded.",
    longDescription:
      "Useful for investors who want EM growth exposure but prefer to manage China risk separately (or skip it entirely). India and Taiwan become much larger weights without China in the mix.",
    category: "broad_market",
    subCategory: "emerging_markets_ex_china",
    ter: "0.0018",
    domicile: "Luxembourg",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 4,
    issuer: "Amundi",
    benchmark: "MSCI EM ex China",
    tags: ["emerging", "ex-china", "global", "core"],
  },
  {
    ticker: "XVTD.L",
    friendlyName: "Vietnamese stocks (swap-based)",
    name: "Xtrackers FTSE Vietnam Swap UCITS ETF 1C",
    shortDescription:
      "Vinhomes, Hoa Phat, Vingroup, Masan, Vietcombank — tracks FTSE Vietnam via synthetic swaps (foreign-ownership rules block direct holding).",
    longDescription:
      "Vietnam restricts foreign ownership of equities, so this ETF uses derivatives (swaps) to replicate the FTSE Vietnam index. That introduces counterparty risk on top of the usual frontier-market risks (illiquidity, governance).",
    category: "region",
    subCategory: "vietnam",
    ter: "0.0085",
    domicile: "Luxembourg",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "Xtrackers",
    benchmark: "FTSE Vietnam",
    tags: ["vietnam", "asia", "emerging", "frontier", "swap"],
  },
  {
    ticker: "XMBR.L",
    friendlyName: "Brazilian stocks (Vale, Petrobras)",
    name: "Xtrackers MSCI Brazil UCITS ETF 1C",
    shortDescription:
      "Vale, Petrobras, Itaú, B3 and other large Brazilian companies. Heavy commodity exposure (iron ore, oil).",
    longDescription:
      "Tracks MSCI Brazil — commodity-heavy. Performance closely follows iron ore and oil prices via Vale and Petrobras. Trades in GBp on LSE.",
    category: "region",
    subCategory: "brazil",
    ter: "0.0065",
    domicile: "Luxembourg",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 5,
    issuer: "Xtrackers",
    benchmark: "MSCI Brazil",
    tags: ["brazil", "emerging", "commodities", "latam"],
  },
  {
    ticker: "XMES.L",
    friendlyName: "Mexican stocks (América Móvil, Walmex)",
    name: "Xtrackers MSCI Mexico UCITS ETF 1C",
    shortDescription:
      "América Móvil, Walmart de México, FEMSA, Banorte and other large Mexican companies.",
    longDescription:
      "Tracks MSCI Mexico. Sometimes pitched as a nearshoring play — Mexico benefits from US manufacturing reshoring trends.",
    category: "region",
    subCategory: "mexico",
    ter: "0.0065",
    domicile: "Luxembourg",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "Xtrackers",
    benchmark: "MSCI Mexico",
    tags: ["mexico", "emerging", "latam", "nearshoring"],
  },
  {
    ticker: "IKSA.L",
    friendlyName: "Saudi Arabian stocks (Aramco capped)",
    name: "iShares MSCI Saudi Arabia Capped UCITS ETF",
    shortDescription:
      "Saudi Aramco (capped at 20%), Al Rajhi Bank, STC, SABIC and other Saudi large caps.",
    longDescription:
      "Tracks MSCI Saudi Arabia Capped — Aramco is capped at 20% to prevent single-stock concentration. Heavy in financials and energy. Pegged to USD via the Saudi riyal so FX is essentially USDSGD.",
    category: "region",
    subCategory: "saudi_arabia",
    ter: "0.0050",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "iShares",
    benchmark: "MSCI Saudi Arabia Capped",
    tags: ["saudi", "middle-east", "emerging", "energy"],
  },

  // ─── Defence alternative ───────────────────────────────────────
  {
    ticker: "DFNS.L",
    friendlyName: "Defense industry (US-tilted)",
    name: "VanEck Defense UCITS ETF",
    shortDescription:
      "The big defense contractors — Lockheed Martin, RTX, Northrop Grumman, General Dynamics, BAE Systems, Boeing, L3Harris. More US-concentrated than the HANetf alternative (NATO).",
    longDescription:
      "Tracks the MarketVector Global Defense Industry Index. Heavy in US prime contractors but includes major European defense names. Listed in March 2023, so it captured the post-Ukraine defense rally from near inception.",
    category: "thematic",
    subCategory: "defence",
    ter: "0.0055",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 4,
    issuer: "VanEck",
    benchmark: "MarketVector Global Defense Industry",
    tags: ["defence", "aerospace", "thematic", "us"],
  },

  // ─── Chinese tech ──────────────────────────────────────────────
  {
    ticker: "HSTC.L",
    friendlyName: "Chinese tech (Hang Seng Tech)",
    name: "HSBC Hang Seng Tech UCITS ETF",
    shortDescription:
      "The Chinese tech giants in one fund — Tencent, Alibaba, Meituan, JD, Xiaomi, NetEase, Baidu, Kuaishou. All listed in Hong Kong. Highly cyclical and very sensitive to Chinese regulation.",
    longDescription:
      "Tracks the Hang Seng Tech Index — the 30 largest tech companies listed in Hong Kong, most of them Chinese. The 'Nasdaq of China' but with much higher regulatory and political risk. Has gone through major drawdowns (-70% from 2021 peak to 2022 trough).",
    category: "thematic",
    subCategory: "china_tech",
    ter: "0.0050",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "GBP",
    riskScore: 5,
    issuer: "HSBC",
    benchmark: "Hang Seng Tech",
    tags: ["china", "tech", "hong-kong", "thematic", "tencent", "alibaba"],
  },

  // ─── More thematics ────────────────────────────────────────────
  {
    ticker: "HEAL.L",
    friendlyName: "Biotech & medical innovation",
    name: "iShares Healthcare Innovation UCITS ETF",
    shortDescription:
      "Cutting-edge healthcare — companies working on gene editing, robotic surgery, AI drug discovery, personalized medicine. More speculative than the broad health-care fund (WHEA).",
    longDescription:
      "Tracks the iSTOXX FactSet Breakthrough Healthcare index. Holds smaller, more innovation-focused companies than mainstream healthcare ETFs. Includes biotech, gene therapy, surgical robotics, and diagnostic AI plays.",
    category: "thematic",
    subCategory: "biotech",
    ter: "0.0040",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "iShares",
    benchmark: "iSTOXX FactSet Breakthrough Healthcare",
    tags: ["biotech", "healthcare", "innovation", "thematic"],
  },
  {
    ticker: "YODA.L",
    friendlyName: "Space economy",
    name: "Procure Space UCITS ETF",
    shortDescription:
      "Companies that earn meaningful revenue from space — satellite operators (SES, Iridium), launch providers, defense aerospace, ground equipment. Mix of established names and small caps.",
    longDescription:
      "Tracks the S-Network Space Index. About half the fund is in companies where space is a primary business; the rest is broader aerospace/defense exposure. Concentrated and small in size — bigger price swings.",
    category: "thematic",
    subCategory: "space",
    ter: "0.0075",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "Procure",
    benchmark: "S-Network Space",
    tags: ["space", "aerospace", "thematic", "innovation"],
  },
  {
    ticker: "ESPO.L",
    friendlyName: "Video games & esports",
    name: "VanEck Video Gaming and eSports UCITS ETF",
    shortDescription:
      "The gaming industry in one fund — Nintendo, Activision, EA, Take-Two, Tencent, Roblox, Nvidia (graphics chips), and esports specialists. Cyclical with gaming hardware cycles.",
    longDescription:
      "Tracks the MVIS Global Video Gaming & eSports Index. Mix of game developers, publishers, streaming platforms, and hardware. Heavy in Japanese, US and Chinese gaming companies.",
    category: "thematic",
    subCategory: "gaming",
    ter: "0.0055",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "VanEck",
    benchmark: "MVIS Global Video Gaming & eSports",
    tags: ["gaming", "esports", "entertainment", "thematic", "tech"],
  },
  {
    ticker: "EBIZ.L",
    friendlyName: "Online retail (e-commerce)",
    name: "Global X E-commerce UCITS ETF",
    shortDescription:
      "Companies that sell online or power online selling — Amazon, Shopify, MercadoLibre, Alibaba, JD.com. Performance closely tied to consumer-spending and tech sentiment.",
    longDescription:
      "Tracks the Solactive E-commerce Logistics Performance Index. Includes online retailers, marketplaces, and the logistics/payments companies that enable them. Tech-adjacent with consumer-discretionary cyclicality.",
    category: "thematic",
    subCategory: "ecommerce",
    ter: "0.0050",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 5,
    issuer: "Global X",
    benchmark: "Solactive E-commerce Logistics",
    tags: ["ecommerce", "consumer", "tech", "thematic"],
  },

  // ─── New themes (luxury, real estate, dividends) ───────────────
  {
    ticker: "LUXG.L",
    friendlyName: "Luxury brands (LVMH, Hermès, Kering)",
    name: "Amundi Global Luxury UCITS ETF USD (Acc)",
    shortDescription:
      "The luxury industry in one fund — LVMH, Hermès, Kering, Richemont, Estée Lauder, Ferrari and other high-end brands. Tends to do well when the wealthy keep spending.",
    longDescription:
      "Tracks S&P Global Luxury — about 80 companies producing luxury goods or services worldwide. Heavily skewed toward European brands but includes US and Asian luxury too. Sensitive to Chinese consumer demand.",
    category: "thematic",
    subCategory: "luxury",
    ter: "0.0025",
    domicile: "Luxembourg",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 4,
    issuer: "Amundi",
    benchmark: "S&P Global Luxury",
    tags: ["luxury", "consumer", "europe", "thematic", "lvmh", "hermes"],
  },
  {
    ticker: "IWDP.L",
    friendlyName: "Global real estate (REITs)",
    name: "iShares Developed Markets Property Yield UCITS ETF",
    shortDescription:
      "Owns a slice of real-estate companies and REITs around the developed world — shopping malls, offices, warehouses, data centres, apartments. Pays out the rental income as dividends.",
    longDescription:
      "Tracks FTSE EPRA/NAREIT Developed Dividend+ — global listed property companies and REITs. Heavy in US (~60%) and Japan. Sensitive to interest rates — rising rates usually hurt REIT prices.",
    category: "thematic",
    subCategory: "real_estate",
    ter: "0.0059",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "FTSE EPRA/NAREIT Developed Dividend+",
    tags: ["reits", "real-estate", "property", "global", "income"],
  },
  {
    ticker: "VHYL.L",
    friendlyName: "Global dividend payers",
    name: "Vanguard FTSE All-World High Dividend Yield UCITS ETF",
    shortDescription:
      "About 1,800 companies worldwide that pay above-average dividends — banks, oil majors, pharma, utilities. Built for income rather than growth.",
    longDescription:
      "Tracks the FTSE All-World High Dividend Yield index. Excludes REITs. Tilted to value sectors — financials, energy, healthcare. Pays dividends quarterly. Lower growth potential than the broad world index but higher cash yield (~3-4%).",
    category: "thematic",
    subCategory: "dividends",
    ter: "0.0029",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "GBP",
    riskScore: 3,
    issuer: "Vanguard",
    benchmark: "FTSE All-World High Dividend Yield",
    tags: ["dividend", "income", "global", "value"],
  },

  // ─── Sustainable / SRI ─────────────────────────────────────────
  {
    ticker: "SUSW.L",
    friendlyName: "Sustainable global stocks",
    name: "iShares MSCI World SRI UCITS ETF EUR (Acc)",
    shortDescription:
      "Same global developed-world exposure as MSCI World, but screens out tobacco, weapons, gambling, fossil fuels, and low-ESG-rated companies — keeping only the best-in-class.",
    longDescription:
      "Tracks the MSCI World SRI Select Reduced Fossil Fuels index. Excludes companies in tobacco, controversial weapons, gambling, alcohol, adult entertainment, fossil fuels, and those with low ESG ratings. About 400 companies remain (vs 1,500 in MSCI World).",
    category: "broad_market",
    subCategory: "world_sri",
    ter: "0.0020",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "EUR",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "MSCI World SRI Select Reduced Fossil Fuels",
    tags: ["world", "developed", "esg", "sri", "sustainable"],
  },
  {
    ticker: "SUUS.L",
    friendlyName: "Sustainable US stocks",
    name: "iShares MSCI USA SRI UCITS ETF",
    shortDescription:
      "The 'ethical S&P 500' equivalent — same US large-cap exposure but excludes weapons, tobacco, fossil fuels, and low-ESG-rated companies.",
    longDescription:
      "Tracks MSCI USA SRI Select Reduced Fossil Fuels — best-in-class US companies after applying ESG screens. Fewer holdings than CSPX.L, with no oil majors or weapons makers.",
    category: "broad_market",
    subCategory: "us_sri",
    ter: "0.0020",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "GBp",
    riskScore: 3,
    issuer: "iShares",
    benchmark: "MSCI USA SRI Select Reduced Fossil Fuels",
    tags: ["us", "esg", "sri", "sustainable"],
  },
  {
    ticker: "SUSM.L",
    friendlyName: "Sustainable emerging-market stocks",
    name: "iShares MSCI EM SRI UCITS ETF USD (Acc)",
    shortDescription:
      "Emerging-market exposure with the same ESG screen — excludes Aramco, PetroChina, weapons makers, tobacco, and the worst-rated ESG companies.",
    longDescription:
      "Tracks MSCI EM SRI Select Reduced Fossil Fuels. Roughly 200 companies (vs 3,000 in broad EM) after screens. Tech and consumer-staples heavy since fossil-fuel-heavy markets like Russia and Saudi Aramco are largely excluded.",
    category: "broad_market",
    subCategory: "emerging_markets_sri",
    ter: "0.0035",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: true,
    exchange: "LSE",
    currency: "USD",
    riskScore: 4,
    issuer: "iShares",
    benchmark: "MSCI EM SRI Select Reduced Fossil Fuels",
    tags: ["emerging", "esg", "sri", "sustainable"],
  },

  // ─── Bonds ──────────────────────────────────────────────────────────────
  {
    ticker: "AGGG.L",
    isin: "IE00B3F81409",
    friendlyName: "Global bonds (safer mix)",
    name: "iShares Core Global Aggregate Bond UCITS ETF",
    shortDescription:
      "Mix of government and company bonds from around the world. Lower risk and return than stocks.",
    longDescription:
      "Broad global bond exposure covering investment-grade government, corporate and securitised debt across developed and emerging markets. Distributing; the Acc sister AGGU.L (IE00BDBRDM35) is recommended for long-term sims.",
    category: "bond",
    subCategory: "global_aggregate",
    ter: "0.0010",
    domicile: "Ireland",
    isUcits: true,
    isAccumulating: false,
    exchange: "LSE",
    currency: "USD",
    riskScore: 2,
    issuer: "iShares",
    benchmark: "Bloomberg Global Aggregate",
    tags: ["bonds", "core", "defensive", "global"],
  },
];
